# Generated by Django 5.0.4 on 2024-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_hash',
            field=models.CharField(default='', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
