# Generated by Django 5.0.4 on 2024-04-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
