# Generated by Django 5.0.4 on 2024-04-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0004_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
