# Generated by Django 5.0.4 on 2024-04-23 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0005_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spent_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
