# Generated by Django 5.0.6 on 2024-05-13 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_hash', models.CharField(default='', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('spent_time', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
