name: Django CI

on:
  push:
    branches: [ "lab3" ]
  pull_request:
    branches: [ "lab3" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Build Django container
      run: |
        docker-compose up -d web
    - name: Run Django migrations
      run: |
        docker compose exec web python manage.py migrate
    - name: Run Django tests
      run: |
        docker compose exec web python manage.py runserver
    - name: Test active ports
      run: |
        sudo lsof -i -P -n | grep LISTEN
